project/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views

from app.views import MyProjLoginView
from app.views import RegisterView, MyProjLogout




urlpatterns = [
    path('admin/', admin.site.urls),
    path('mexel/', views.mexel, name='mexel'),
    path('tumar/', views.tumar, name='tumar'),
    path('alanda/', views.alanda, name='alanda'),
    path('senim/', views.senim, name='senim'),
    path('mua/', views.mua, name='mua'),
    path('city/', views.city, name='city'),
    path('erzh/', views.erzh, name='erzh'),
    path('ymit/', views.ymit, name='ymit'),
    path('zhan/', views.zhan, name='zhan'),
    path('damu/', views.damu, name='damu'),
    path('ansar/', views.ansar, name='ansar'),
    path('profile/', views.home, name='home'),
    path('schedule/', views.schedule, name='schedule'),

    path('', views.index, name='index'),
    path('login', views.MyProjLoginView.as_view(), name='login'),
    path('about', views.about, name='about'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('hospital_form/', views.hospital_form_view, name='hospital_form'),
    path('appointment_form/', views.appointment_form_view, name='appointment_form'),
 
]



   

app/models.py
# models.py
from django.contrib.auth.models import User
from django.db import models

class Doctor(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    experience = models.IntegerField()
    specialization = models.CharField(max_length=255)
    hospitals = models.ForeignKey('Hospital', on_delete=models.CASCADE, related_name='doctors', null=True)

    def str(self):
        return self.first_name + ' ' + self.last_name

class Hospital(models.Model):
    title = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=20)

    def str(self):
        return self.title

class Appointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hospital = models.ForeignKey('Hospital', on_delete=models.CASCADE)
    doctor = models.ForeignKey('Doctor', on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()

templates/appointment_form.html
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/pharm.css' %}">
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/png">
</head>
<body>
<div class="header">
  <p>
    <img src="/static/images/KazPharmEm.png" alt="KazPharm logo" height="100px" width="100px">
  </p>
  <div class="header-text">
    <li><a href="{% url 'index' %}">Главная</a></li>
    <li><a href="{% url 'hospital_form' %}">Запись</a></li>
    <li><a href="{% url 'about' %}">Больницы</a></li>
    <li><a href="https://t.me/KazPharmAmbulanceBot">Контакты</a></li>

    {% if request.user.is_authenticated %}
            <li><a href="#"> {{ user.username }}</a></li>
            <li><a href="{% url 'logout' %}">Выйти</a></li>
        {% else %}

            <li><a href="{% url 'logout' %}">Выйти</a></li>
           <color="white"> <li><a href="{% url 'home' %}"> {{ user.username }}</a></li>
          <!-- </font> -->
        {% endif %}
  </div>
</div>
<div class="footer">
<p>&copy; KazPharm 2023</p>
</div>
<style>
.header {
    /* width: 80%; */
    height: 100px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin: 0 auto;
    background-color:#133657;
    padding: 0 20px;
    color: #ffffff;
    font-family: 'Times New Roman', Times, serif;
}

.header-text {
    display: flex;
}

.header-text :hover {
    color: rgb(94, 163, 227);
}

.header-text li {
    margin-left: 20px;
    font-size: 15px;
    padding-right: 30px;
}

body {
  background-image: url("{% static 'images/11.jpg' %}");
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
  color: #133657;
  height: 100vh;
  font-family: 'Times New Roman', Times, serif;
}

body::before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  z-index: -1;
  background-attachment: fixed;
}

.footer {
    background-color:#133657;
    color: aliceblue;
    padding: 15px;
    text-align: center;
    bottom: 0;
    left: 0;
    position: fixed;
    width: 100%;
  }

/* ЗАПИСЬ */

/* Normalize styles for consistent cross-browser rendering */
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

h2 {
  margin-top: 20px;
  text-align: center;
  font-weight: 400; /* Slightly lighter heading for visual hierarchy */
}

form {
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 100%;
  max-width: 500px;
  margin: 20px auto;
  padding: 20px;
  border: 1px solid #091b2b;
  border-radius: 5px;
  background-color: #fff;
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1); /* Subtle shadow for depth */
}

label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
}

input,
select {
  width: 100%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 3px;
  margin-bottom: 10px;
}

input[type="submit"] {
  background-color: #133657; /* Primary blue color for emphasis */
  color: #fff;
  cursor: pointer;
}

/* Optional: Add subtle hover effect for interactivity */
input[type="submit"]:hover {
  background-color: #091b2b; /* Slightly darker blue on hover */
}

</style>

<h2>Выбранная больница: {{ hospital.title }}</h2><br>

<form method="post" action="{% url 'appointment_form' %}">
    {% csrf_token %}
    <input type="hidden" name="hospital_id" value="{{ hospital.id }}">

    <label for="id_doctor">Врач:</label>
    <select name="doctor_id" id="id_doctor" required>
        {% for doctor in doctors %}
            <option value="{{ doctor.id }}">{{ doctor.first_name }} {{ doctor.last_name }}</option>
        {% endfor %}
    </select>

    <br>

    <label for="id_date">Дата записи:</label>
    <input type="date" name="date" id="id_date" required>

    <br>

    <label for="id_time">Время записи:</label>
    <input type="time" name="time" id="id_time" required>

    <br>

    <input type="submit" value="Записаться">
</form>
<div class="container">
  {% block content %}{% endblock %}
</div>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Запись</title>
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/png">
</head>

<body>
    <div class="header">
        <p>
            <img src="/static/images/KazPharmEm.png" alt="KazPharm logo" height="100px" width="100px">
        </p>
        <div class="header-text">
            <li><a href="{% url 'index' %}">Главная</a></li>
            <li><a href="{% url 'hospital_form' %}">Запись</a></li>
            <li><a href="{% url 'about' %}">Больницы</a></li>
            <li><a href="https://t.me/KazPharmAmbulanceBot">Контакты</a></li>

            {% if request.user.is_authenticated %}
            <li><a href="{% url 'home' %}"> {{ user.username }}</a></li>
            <li><a href="{% url 'logout' %}">Выйти</a></li>
            {% else %}
            <li><a href="{% url 'register' %}">Зарегестрироваться</a></li>
            <li><a href="{% url 'login' %}">Выйти</a></li>
            {% endif %}
        </div>
    </div><br><br>


    <style>
        .b {
            /* background: #2b4c60; */
            color:#ffffff;
            

        }


        .appointments{
            background: #2b4c60;
            color:#bcdcf0;
            padding-left: 20px;

        }

        body {
  background-image: url("{% static 'images/11.jpg' %}");
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
  color: aliceblue;
  height: 100vh;
}

body::before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100vh;
  background-color: rgba(0, 0, 0, 0.5);
  z-index: -1;
  background-attachment: fixed;
}
        * {
            margin: 0;
            padding: 0;
        }

        li,
        a {
            list-style: none;
            text-decoration: none;
            color: #ffffff;
            font-size: 20px;
        }

        .header a {
            list-style: none;
            text-decoration: none;
            color: #ffffff;
            font-size: 20px;
        }



        .header {
            /* width: 80%; */
            height: 100px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            margin: 0 auto;
            background-color: #133657;
            padding: 0 20px;
            color: #ffffff;
            font-family: 'Times New Roman', Times, serif;
        }

        .header-text {
            display: flex;
        }

        .header-text :hover {
            color: rgb(94, 163, 227);
        }

        .header-text li {
            margin-left: 20px;
            font-size: 15px;
            padding-right: 30px;
        }

        .footer {
            width: 100%;
            position: absolute;
            bottom: 0;
            right: 0;
            text-align: center;
            padding: 15px;
            background-color: #000000;
            color: #fff;
            font-family: 'Roboto', Arial, sans-serif;
        }

        .footer p {
            color: aliceblue;
        }


        /* //////// */

        .cont {
            width: 100%;
            height: 100vh;
            background-image: linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)),
            url("{% static 'images/11.jpg' %}");
            background-position: center;
            background-size: cover;
            padding-left: 8%;
            padding-right: 8%;
            box-sizing: border-box;
            margin-top: -37px;
        }



        .row {
            display: flex;
            height: 88%;
            align-items: center;
        }

        .col {
            flex-basis: 50%;
        }

        h1 {
            color: #fff;
            font-size: 100px;
        }

        button {
            width: 280px;
            color: #ffffff;
            font-size: 18px;
            padding: 14px 0;
            background: #154360;
            border: 0;
            border-radius: 20px;
            outline: none;
            margin-top: 30px;
        }

        button :hover {
            width: 280px;
            font-size: 18px;
            padding: 14px 0;
            border: 0;
            border-radius: 20px;
            outline: none;
            margin-top: 30px;
            background: #154360;
        }

        a {
            text-decoration: none;
            color: #ffffff;
        }
    </style>


    <div class="container">
        {% block content %}
        {% endblock %}

        <div class="footer">
            <p>&copy; KazPharm 2023</p>
        </div>
    </div>
</body>

</html>

templates/home.html
{% load static %}
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}Profile{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/pharm.css' %}">
  <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/png">
</head>

<body>
  <div class="header">
    <h1>
      <img src="/static/images/KazPharmEm.png" alt="KazPharm logo" height="100px" width="100px">
    </h1>
    <div class="header-text">
      <li><a href="{% url 'index' %}">Главная</a></li>
      <li><a href="{% url 'hospital_form' %}">Запись</a></li>
      <li><a href="{% url 'about' %}">Больницы</a></li>
      <li><a href="https://t.me/KazPharmAmbulanceBot">Контакты</a></li>

      {% if request.user.is_authenticated %}
      <li><a href="#"> {{ user.username }}</a></li>
      <li><a href="{% url 'logout' %}">Выйти</a></li>
      {% else %}

      <li><a href="{% url 'logout' %}">Выйти</a></li>
      <color="white">
        <li><a href="{% url 'home' %}"></a> {{ user.username }}</a></li>
        <!-- </font> -->
        {% endif %}
    </div>
  </div>



  <style>
    .header {
      /* width: 80%; */
      height: 100px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin: 0 auto;
      background-color: #133657;
      padding: 0 20px;
      color: #ffffff;
    }

    .header-text {
      display: flex;
    }

    .header-text :hover {
      color: rgb(94, 163, 227);
    }

    .header-text li {
      margin-left: 20px;
      font-size: 15px;
      padding-right: 30px;
    }

    body {
      background-image: url("{% static 'images/11.jpg' %}");
      background-repeat: no-repeat;
      background-position: center;
      background-size: cover;
      color: aliceblue;
      height: 100vh;
    }

    body::before {
      content: "";
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100vh;
      background-color: rgba(0, 0, 0, 0.5);
      z-index: -1;
      background-attachment: fixed;
    }

    .footer {
      width: 100%;
      position: absolute;
      bottom: 0;
      right: 0;
      text-align: center;
      padding: 15px;
      background-color: #000000;
      color: #fff;
      font-family: 'Roboto', Arial, sans-serif;
    }


    /* код для личного кабинета */
    /* Overall form styling */
    .container {
      max-width: 500px;
      /* Adjust width as needed */
      margin: 40px auto;
      font-family: sans-serif;
    }

    .row {
      margin-bottom: 20px;
    }

    .form-group label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;
    }

    input[type="text"],
    input[type="email"],
    input[type="file"] {
      width: 100%;
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 5px;
      box-sizing: border-box;
      margin-bottom: 10px;
    }

    /* Button styling */
    .btn-info {
      background-color: #133657;
      /* Dark blue */
      border-color: #0d263d;
      color: #fff;
      font-weight: bold;
      padding: 10px 20px;
      border-radius: 5px;
      cursor: pointer;
    }

    .btn-block {
      display: block;
      width: 100%;
    }

    /* Image styling */
    .img-thumbnail {
      border: 1px solid #ccc;
      border-radius: 5px;
      /* margin-bottom: 5px; */
    }
  </style>


  <div class="content">
    {% block content %}
    ⠀⠀{{request.user.username}}
    ⠀<a href="{% url 'schedule' %}">Записи приемов</a>

    <div class="container">
      <div class="row">
        <div class="col-lg-7">
          <h4 class="mt-3 mb-3">Профиль</h4><br>
          <!-- <div class="col-lg-12 text-center">
                      <img width="100" height="100"
                           src=""
                           class="img-thumbnail">
                  </div> -->
          <form action="{% url 'home' %}" method="post">
            {% csrf_token %}
            <div class="form-row">
              <div class="col-lg-6">
                <div class="form-group">
                  <label class="small mb-1" for="{{ form.email.id_for_label}}">Имя пользователя</label>
                  {{ form.username }}
                </div>
              </div>
              <div class="col-lg-6">
                <div class="form-group">
                  <label class="small mb-1" for="{{ form.email.id_for_label}}">
                    Адрес электроннй почны
                  </label>
                  {{ form.email }}
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.first_name.id_for_label}}">
                  Имя
                </label>
                {{ form.first_name }}
              </div>
              <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.last_name.id_for_label}}">
                  Фамилия
                </label>
                {{ form.last_name }}
              </div>
            </div>
            <div class="form-row">
              <div class="col-lg-12" style="margin-top: 33px;">

                <a href="{% url 'home' %}"> <input class="btn btn-info btn-block" type="submit" value="Сохранить"></a>
              </div>
            </div>
          </form>
        </div>



        </li>
        </ul>
      </div>
    </div>
  </div>
  {% endblock %}
  </div>

  <div class="footer">
    <p>&copy; KazPharm 2023</p>
  </div>
  </div>

  <script>
    const avatarInput = document.getElementById("avatar-input");
    const profileImage = document.getElementById("profile-image");

    avatarInput.addEventListener("change", function () {
      const reader = new FileReader();

      reader.onload = function () {
        profileImage.src = reader.result;
      };

      reader.readAsDataURL(avatarInput.files[0]);
    });
  </script>
</body>

</html>

templates/login.html
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/pharm.css' %}">
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/png">
</head>
<body>
<div class="header">
  <h1>
    <img src="/static/images/KazPharmEm.png" alt="KazPharm logo" height="100px" width="100px">
  </h1>
  <div class="header-text">
    <li><a href="{% url 'login' %}">Войти</a></li>
      <li><a href="https://t.me/KazPharmAmbulanceBot">Контакты</a></li>

    {% if request.user.is_authenticated %}
            <li><a href="#"> {{ user.username }}</a></li>
            <li><a href="{% url 'logout' %}">Выйти</a></li>
        {% else %}
            <li><a href="{% url 'register' %}">Зарегестрироваться</a></li>
        {% endif %}
  </div>
</div>
<div class="footer">
<p>&copy; KazPharm 2023</p>
</div>
<style>
.header {
    /* width: 80%; */
    height: 100px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin: 0 auto;
    background-color:#133657;
    padding: 0 20px;
    color: #ffffff;
}

.header-text {
    display: flex;
}

.header-text :hover {
    color: rgb(94, 163, 227);
}

.header-text li {
    margin-left: 20px;
    font-size: 15px;
    padding-right: 30px;
}

body {
  background-image: url("{% static 'images/11.jpg' %}");
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
  color: aliceblue;
  height: 100vh;
}

body::before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  z-index: -1;
  background-attachment: fixed;
}

.footer {
    background-color:#000000;
    color: aliceblue;
    padding: 15px;
    text-align: center;
    bottom: 0;
    left: 0;
    position: fixed;
    width: 100%;
  }
</style>




    <h2>     Мы рады приветствовать Вас<br>
        на главной странице Комплексной<br> медицинской
        информационной системы <br>KazPharm</h2>
        <div class="main-w3layouts wrapper">
            <h1>Войдите в аккаунт</h1>
            <div class="main-agileinfo">
              <div class="agileits-top">
                <form id="add_form", method="post">
                  {% csrf_token %}
                  <div class="wthree-text">
                    <div class="clear"> </div>
                  </div>
                  {{ form }}
                  <a href="{% url 'home' %}"><center><input type="submit" value="Войти"></center></a>
                </form>
                <p>У вас нет аккаунта? <a href="{% url 'register' %}">Зарегестрироваться</a></p>
              </div>
            </div>
          </div>

<div class="container">
{% block content %}{% endblock %}
</div>
</body>
</html>

templates/schedule.html
{% extends 'base.html' %}

{% block title %}
Успешно записано
{% endblock %}

{% block content %}

{% for i in appointments %}
<div class="appointments"></div>
⠀⠀⠀⠀Клиника в которую вы записались:⠀{{i.hospital.title}}<br>
⠀⠀⠀⠀Имя доктора:⠀{{i.doctor.first_name}}<br>
⠀⠀⠀⠀Фамилия доктора:⠀{{i.doctor.last_name}}<br>
⠀⠀⠀⠀Дата записи:⠀{{i.date}}<br>
⠀⠀⠀⠀Время записи⠀{{i.time}}<br><br> 
</div>


{% endfor %}
{% endblock %}